name: Issue Form
description: Issue form for SSDA-front
labels: [order]

title: "SSDA"

body:
  - type: input
    id: Description
    attributes:
      label: 이슈 내용 (Description)
    validations:
      required: true

  - type: textarea
    id: Details
    attributes:
      label: 상세 내용 (Details)
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 체크리스트 (Tasks)
      options:
        - label: task1
        - label: task2
          required: false

  - type: input
    id: Link
    attributes:
      label: 참조 (References)
    validations:
      required: false
