name: 'SSDA Front Issue 생성'
description: 'SSDA Front Repo에 Issue를 생성합니다. 생성된 Issue는 Jira와 연동됩니다.'
labels: [order]
title: 'Issue 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '상위 작업 Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'DIAR-00'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '이슈 작성'
      description: '이슈에 대해서 설명해주세요'
      value: |
        **이슈 내용(Description)**
        - 

        **상세 내용(Details)**
        - 

        **체크리스트(Tasks)**
        - [ ] Task1
        - [ ] Task2

        **참조(References)**
        - 
    validations:
      required: true
